services:
  python-api:
    container_name: python-api
    build:
      context: ./api
    image: python-api-image
    volumes:
      - ./volumes/logs:/opt/python-api/logs
    ports:
      - "8000:8000"
    environment:
      - MONGODB_HOST
      - MONGODB_PORT
      - TZ
    networks:
      - mongodb-net
    depends_on:
      - mongodb
    restart: always
    profiles:
      - api

  mongodb:
    container_name: mongodb
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - mongodb-net
    restart: always
    profiles:
      - db

  api-monitor:
    image: api-monitor
    build:
      context: api-monitor/
      dockerfile: Dockerfile.monitor
    container_name: api-monitor
    hostname: api-monitor
    networks:
      - mongodb-net
    environment:
      - CHECK_INTERVAL               # Intervalo de tiempo entre cada verificación.
      - TARGET_CONTAINER_HOST        # Nombre del host del contenedor objetivo.
      - TARGET_CONTAINER_PORT        # Puerto del contenedor objetivo.
      - TZ                           # Zona horaria del contenedor.
    volumes:
      - ./volumes/logs/api-monitor.log:/opt/api-monitor/logs/api-monitor.log
    depends_on:
     - python-api
    ports:
      - "8001:80"
    restart: always
    profiles:
      - back
      - monitor

networks:
  mongodb-net:

volumes:
  mongo-data:
