# Usamos la imagen base de Python 3.12 slim
FROM python:3.12-slim

# Establecemos el directorio de trabajo
WORKDIR /opt/api-monitor

# Crea un entorno virtual
RUN python3 -m venv venv

# Directorios necesarios
RUN mkdir -p /opt/api-monitor/logs

# Script monitoreo y archivo requirements.txt
COPY . .

# Instalar la librería 'requests' en el entorno virtual
RUN /opt/api-monitor/venv/bin/pip install --no-cache-dir requests

# Expone el puerto 80.
EXPOSE 80

# Comando que se ejecuta cuando el contenedor inicia.
CMD ["/opt/api-monitor/venv/bin/python", "monitor-script.py"]